/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.side.bar.menu.buttons;

import java.awt.CardLayout;

/**
 *
 * @author Kenenias B. Perez
 */
public class Main extends javax.swing.JFrame {

    private CardLayout cardLayout;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        cardLayout = (CardLayout) pnlCards.getLayout();
    }
    
    public void showComponents(){

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnlCards = new javax.swing.JPanel();
        pnlCardRed = new javax.swing.JPanel();
        pnlCardGreen = new javax.swing.JPanel();
        pnlCardYellow = new javax.swing.JPanel();
        pnlLeft = new javax.swing.JPanel();
        btnRed = new javax.swing.JButton();
        btnGreen = new javax.swing.JButton();
        btnYellow = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCards.setLayout(new java.awt.CardLayout());

        pnlCardRed.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout pnlCardRedLayout = new javax.swing.GroupLayout(pnlCardRed);
        pnlCardRed.setLayout(pnlCardRedLayout);
        pnlCardRedLayout.setHorizontalGroup(
            pnlCardRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );
        pnlCardRedLayout.setVerticalGroup(
            pnlCardRedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        pnlCards.add(pnlCardRed, "card4");

        pnlCardGreen.setBackground(new java.awt.Color(0, 204, 51));

        javax.swing.GroupLayout pnlCardGreenLayout = new javax.swing.GroupLayout(pnlCardGreen);
        pnlCardGreen.setLayout(pnlCardGreenLayout);
        pnlCardGreenLayout.setHorizontalGroup(
            pnlCardGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );
        pnlCardGreenLayout.setVerticalGroup(
            pnlCardGreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        pnlCards.add(pnlCardGreen, "card3");

        pnlCardYellow.setBackground(new java.awt.Color(204, 255, 0));

        javax.swing.GroupLayout pnlCardYellowLayout = new javax.swing.GroupLayout(pnlCardYellow);
        pnlCardYellow.setLayout(pnlCardYellowLayout);
        pnlCardYellowLayout.setHorizontalGroup(
            pnlCardYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );
        pnlCardYellowLayout.setVerticalGroup(
            pnlCardYellowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        pnlCards.add(pnlCardYellow, "card2");

        jSplitPane1.setRightComponent(pnlCards);

        btnRed.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 18)); // NOI18N
        btnRed.setText("Red");
        btnRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedActionPerformed(evt);
            }
        });

        btnGreen.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        btnGreen.setText("Green");
        btnGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGreenActionPerformed(evt);
            }
        });

        btnYellow.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        btnYellow.setText("Yellow");
        btnYellow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYellowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLeftLayout = new javax.swing.GroupLayout(pnlLeft);
        pnlLeft.setLayout(pnlLeftLayout);
        pnlLeftLayout.setHorizontalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRed, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnYellow)))
        );
        pnlLeftLayout.setVerticalGroup(
            pnlLeftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeftLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(btnRed)
                .addGap(7, 7, 7)
                .addComponent(btnGreen)
                .addGap(12, 12, 12)
                .addComponent(btnYellow))
        );

        jSplitPane1.setLeftComponent(pnlLeft);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedActionPerformed
        pnlCards.removeAll();
        pnlCards.add(pnlCardRed);
        pnlCards.repaint();
        pnlCards.revalidate();
        
    }//GEN-LAST:event_btnRedActionPerformed

    private void btnGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGreenActionPerformed
        pnlCards.removeAll();
        pnlCards.add(pnlCardGreen);
        pnlCards.repaint();
        pnlCards.revalidate();
    }//GEN-LAST:event_btnGreenActionPerformed

    private void btnYellowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYellowActionPerformed
        pnlCards.removeAll();
        pnlCards.add(pnlCardYellow);
        pnlCards.repaint();
        pnlCards.revalidate();
    }//GEN-LAST:event_btnYellowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGreen;
    private javax.swing.JButton btnRed;
    private javax.swing.JButton btnYellow;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlCardGreen;
    private javax.swing.JPanel pnlCardRed;
    private javax.swing.JPanel pnlCardYellow;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JPanel pnlLeft;
    // End of variables declaration//GEN-END:variables
}
