/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.kene.swing.ui.design;

import java.awt.Color;
import java.awt.Point;
import javax.swing.JPanel;

/**
 *
 * @author macos
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBg = new javax.swing.JPanel();
        pnlSide = new javax.swing.JPanel();
        pnlSide1 = new javax.swing.JPanel();
        btnEmployee = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnIncentives = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnComing = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnAdministracion = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        btnDocument = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        choice1 = new java.awt.Choice();
        choice2 = new java.awt.Choice();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        pnlBg.setBackground(new java.awt.Color(255, 255, 255));
        pnlBg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pnlBgFocusLost(evt);
            }
        });
        pnlBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSide.setBackground(new java.awt.Color(54, 33, 89));
        pnlSide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSide1.setBackground(new java.awt.Color(54, 33, 89));
        pnlSide1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmployee.setBackground(new java.awt.Color(85, 65, 118));
        btnEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEmployeeMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Beneficios Empleados");

        javax.swing.GroupLayout btnEmployeeLayout = new javax.swing.GroupLayout(btnEmployee);
        btnEmployee.setLayout(btnEmployeeLayout);
        btnEmployeeLayout.setHorizontalGroup(
            btnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEmployeeLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
        btnEmployeeLayout.setVerticalGroup(
            btnEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pnlSide1.add(btnEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 109, 240, 40));

        btnIncentives.setBackground(new java.awt.Color(64, 43, 100));
        btnIncentives.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnIncentivesMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Estimulo Empleados");

        javax.swing.GroupLayout btnIncentivesLayout = new javax.swing.GroupLayout(btnIncentives);
        btnIncentives.setLayout(btnIncentivesLayout);
        btnIncentivesLayout.setHorizontalGroup(
            btnIncentivesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIncentivesLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
        btnIncentivesLayout.setVerticalGroup(
            btnIncentivesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnIncentivesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(9, 9, 9))
        );

        pnlSide1.add(btnIncentives, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 240, 40));

        btnComing.setBackground(new java.awt.Color(64, 43, 100));
        btnComing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnComingMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText(" Muy Pronto");

        javax.swing.GroupLayout btnComingLayout = new javax.swing.GroupLayout(btnComing);
        btnComing.setLayout(btnComingLayout);
        btnComingLayout.setHorizontalGroup(
            btnComingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnComingLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(62, 62, 62))
        );
        btnComingLayout.setVerticalGroup(
            btnComingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnComingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pnlSide1.add(btnComing, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, -1));

        btnAdministracion.setBackground(new java.awt.Color(64, 43, 100));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Administración");

        javax.swing.GroupLayout btnAdministracionLayout = new javax.swing.GroupLayout(btnAdministracion);
        btnAdministracion.setLayout(btnAdministracionLayout);
        btnAdministracionLayout.setHorizontalGroup(
            btnAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAdministracionLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(74, 74, 74))
        );
        btnAdministracionLayout.setVerticalGroup(
            btnAdministracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAdministracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pnlSide1.add(btnAdministracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, -1));

        btnDocument.setBackground(new java.awt.Color(64, 43, 100));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Almacenamiento Docs");

        javax.swing.GroupLayout btnDocumentLayout = new javax.swing.GroupLayout(btnDocument);
        btnDocument.setLayout(btnDocumentLayout);
        btnDocumentLayout.setHorizontalGroup(
            btnDocumentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDocumentLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(74, 74, 74))
        );
        btnDocumentLayout.setVerticalGroup(
            btnDocumentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDocumentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pnlSide1.add(btnDocument, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, -1));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        pnlSide1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 190, 10));

        jLabel14.setFont(new java.awt.Font("Al Bayan", 1, 18)); // NOI18N
        jLabel14.setText("Kenenias Bethuel");
        pnlSide1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 160, -1));

        pnlSide.add(pnlSide1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 530));

        pnlBg.add(pnlSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 540));

        jPanel2.setBackground(new java.awt.Color(110, 89, 222));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Administracion/Fondos");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Historial transacciones para____________________________________");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(459, 459, 459))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pnlBg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 620, 140));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Adobe Gothic Std", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"2/7/2020", "08991", "Criek"},
                {"2/8/2020", "88990", "Luke"},
                {"2/7/2020", "37889", "Rose"},
                {null, null, null},
                {null, null, null},
                {null, "", null}
            },
            new String [] {
                "FECHA", "REF. NO", "PARTICULARES"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jTable1.setRowHeight(26);
        jTable1.setSelectionBackground(new java.awt.Color(110, 89, 222));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(10);
        }

        pnlBg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 600, 210));
        pnlBg.add(choice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 180, -1));
        choice1.getAccessibleContext().setAccessibleDescription("");

        pnlBg.add(choice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 180, -1));
        choice2.getAccessibleContext().setAccessibleDescription("");

        jLabel9.setFont(new java.awt.Font("Al Bayan", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        pnlBg.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 20, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBg, javax.swing.GroupLayout.PREFERRED_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        System.exit(0); 
    }//GEN-LAST:event_jLabel9MousePressed

    private void pnlBgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pnlBgFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlBgFocusLost

    private void btnEmployeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeeMousePressed
        setColor(btnEmployee);
        resetColor(btnIncentives);
        resetColor(btnComing);
    }//GEN-LAST:event_btnEmployeeMousePressed

    private void btnIncentivesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIncentivesMousePressed
        setColor(btnIncentives);
        resetColor(btnComing);
        resetColor(btnEmployee);
    }//GEN-LAST:event_btnIncentivesMousePressed

    private void btnComingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComingMousePressed
        setColor(btnComing);
        resetColor(btnIncentives);
        resetColor(btnEmployee);
    }//GEN-LAST:event_btnComingMousePressed

     private Point mouseDownCompCoords = null;
    
    
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
         mouseDownCompCoords = evt.getPoint();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        Point currCoords = evt.getLocationOnScreen();
        this.setLocation(currCoords.x - mouseDownCompCoords.x, currCoords.y - mouseDownCompCoords.y);
    }//GEN-LAST:event_formMouseDragged

    public void setColor(JPanel panel){
        panel.setBackground(new Color(85,65,118));
    }
    
    
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(64,43,100));
         
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAdministracion;
    private javax.swing.JPanel btnComing;
    private javax.swing.JPanel btnDocument;
    private javax.swing.JPanel btnEmployee;
    private javax.swing.JPanel btnIncentives;
    private java.awt.Choice choice1;
    private java.awt.Choice choice2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlBg;
    private javax.swing.JPanel pnlSide;
    private javax.swing.JPanel pnlSide1;
    // End of variables declaration//GEN-END:variables
}
