/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.restaurante.gui;

/**
 *
 * Clase que inicia el Frame principal donde se encuentra el menu 
 * de la aplicacion del restaurante
 * @author Josue Palemon Perez
 * @version 1.0 
 */
public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * Inicia los componentes graficos
     */
    public PrincipalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        mnbRestaurante = new javax.swing.JMenuBar();
        mnuPersonal = new javax.swing.JMenu();
        mniAltaPersonal = new javax.swing.JMenuItem();
        mniModificarPersonal = new javax.swing.JMenuItem();
        mniBajaPersonal = new javax.swing.JMenuItem();
        mnuVentas = new javax.swing.JMenu();
        mniRegistroVentas = new javax.swing.JMenuItem();
        mnuInventario = new javax.swing.JMenu();
        mnuNomina = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mnuPersonal.setText("Personal");

        mniAltaPersonal.setText("Alta");
        mniAltaPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniAltaPersonalActionPerformed(evt);
            }
        });
        mnuPersonal.add(mniAltaPersonal);

        mniModificarPersonal.setText("Modificar");
        mnuPersonal.add(mniModificarPersonal);

        mniBajaPersonal.setText("Baja");
        mnuPersonal.add(mniBajaPersonal);

        mnbRestaurante.add(mnuPersonal);

        mnuVentas.setText("Ventas");

        mniRegistroVentas.setText("Registro Ventas");
        mniRegistroVentas.setToolTipText("");
        mnuVentas.add(mniRegistroVentas);

        mnbRestaurante.add(mnuVentas);

        mnuInventario.setText("Inventario");
        mnbRestaurante.add(mnuInventario);

        mnuNomina.setText("Nomina");
        mnbRestaurante.add(mnuNomina);

        setJMenuBar(mnbRestaurante);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniAltaPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniAltaPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniAltaPersonalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar mnbRestaurante;
    private javax.swing.JMenuItem mniAltaPersonal;
    private javax.swing.JMenuItem mniBajaPersonal;
    private javax.swing.JMenuItem mniModificarPersonal;
    private javax.swing.JMenuItem mniRegistroVentas;
    private javax.swing.JMenu mnuInventario;
    private javax.swing.JMenu mnuNomina;
    private javax.swing.JMenu mnuPersonal;
    private javax.swing.JMenu mnuVentas;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
