package mx.com.empleado.view;

import javax.swing.JOptionPane;
import mx.com.empleado.dao.PersonaDao;
import mx.com.empleado.entity.Persona;

public class FrmPersona extends javax.swing.JFrame {

    private PersonaDao pdao = new PersonaDao();

    /**
     * Creates new form FrmPersona
     */
    public FrmPersona() {
        initComponents();
        limpiarCampos();
        this.setTitle("Formulario Persona");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        mostrarTabla("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneFrmPersona = new javax.swing.JPanel();
        lblTelefono = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        scpPersonaDatos = new javax.swing.JScrollPane();
        tblPersonaDatos = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnBuscarId = new javax.swing.JButton();
        btnBuscarNombres = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paneFrmPersona.setBackground(new java.awt.Color(255, 255, 255));
        paneFrmPersona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTelefono.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTelefono.setText("TELEFONO:");
        paneFrmPersona.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setText("FORMULARIO PERSONA");
        paneFrmPersona.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        lblId.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblId.setText("ID:");
        paneFrmPersona.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblNombre.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblNombre.setText("NOMBRE:");
        paneFrmPersona.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblApellidos.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblApellidos.setText("APELLIDOS:");
        paneFrmPersona.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblEdad.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblEdad.setText(" EDAD:");
        paneFrmPersona.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        paneFrmPersona.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 280, -1));

        txtId.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        paneFrmPersona.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 150, -1));

        txtNombre.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        paneFrmPersona.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 150, -1));

        txtApellidos.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        paneFrmPersona.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 280, -1));

        txtEdad.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        paneFrmPersona.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 280, -1));

        btnLimpiar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        paneFrmPersona.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 260, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        paneFrmPersona.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        btnModificar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        paneFrmPersona.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, -1, -1));

        tblPersonaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPersonaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPersonaDatosMouseClicked(evt);
            }
        });
        scpPersonaDatos.setViewportView(tblPersonaDatos);

        paneFrmPersona.add(scpPersonaDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 460, 240));

        btnEliminar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        paneFrmPersona.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        btnBuscarId.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBuscarId.setText("BUSCAR");
        btnBuscarId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarIdActionPerformed(evt);
            }
        });
        paneFrmPersona.add(btnBuscarId, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 120, 30));

        btnBuscarNombres.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBuscarNombres.setText("BUSCAR");
        btnBuscarNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombresActionPerformed(evt);
            }
        });
        paneFrmPersona.add(btnBuscarNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 120, 30));

        btnCerrarSesion.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnCerrarSesion.setText("CERRAR SESION");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        paneFrmPersona.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, -1, -1));

        getContentPane().add(paneFrmPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 0, 890, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (txtNombre.getText().equals("")
                || txtApellidos.getText().equals("")
                || txtEdad.getText().equals("")
                || txtTelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
        } else {
            String nombres = txtNombre.getText();
            String apellidos = txtApellidos.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            String telefono = txtTelefono.getText();
            String mensaje = pdao.insertarPersona(nombres, apellidos, edad, telefono);
            JOptionPane.showMessageDialog(null, mensaje);
            mostrarTabla("");
            limpiarCampos();

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        char c = evt.getKeyChar();

        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed

        if (txtId.getText().equals("")
                || txtNombre.getText().equals("")
                || txtApellidos.getText().equals("")
                || txtEdad.getText().equals("")
                || txtTelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
        } else {
            int id = Integer.parseInt(txtId.getText());
            String nombres = txtNombre.getText();
            String apellidos = txtApellidos.getText();
            int edad = Integer.parseInt(txtEdad.getText());
            String telefono = txtTelefono.getText();
            String mensaje = pdao.actualizarPersona(id, nombres, apellidos, edad, telefono);
            JOptionPane.showMessageDialog(null, mensaje);
            mostrarTabla("");
            limpiarCampos();
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        String telefono = txtTelefono.getText();
        if (telefono.length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblPersonaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPersonaDatosMouseClicked
        int selected = tblPersonaDatos.getSelectedRow();
        txtId.setText(tblPersonaDatos.getValueAt(selected, 0) + "");
        txtNombre.setText(tblPersonaDatos.getValueAt(selected, 1) + "");
        txtApellidos.setText(tblPersonaDatos.getValueAt(selected, 2) + "");
        txtEdad.setText(tblPersonaDatos.getValueAt(selected, 3) + "");
        txtTelefono.setText(tblPersonaDatos.getValueAt(selected, 4) + "");
    }//GEN-LAST:event_tblPersonaDatosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if (txtId.getText().equals("")
                || txtNombre.getText().equals("")
                || txtApellidos.getText().equals("")
                || txtEdad.getText().equals("")
                || txtTelefono.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos los campos son obligatorios");
        } else {
            int id = Integer.parseInt(txtId.getText());
            String mensaje = pdao.eliminarPersona(id);
            JOptionPane.showMessageDialog(null, mensaje);
            mostrarTabla("");
            limpiarCampos();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarIdActionPerformed
        if(txtId.getText().equals("")){
            JOptionPane.showMessageDialog(null, "El campo de id esta vacio");
        }else{
            int id = Integer.parseInt(txtId.getText());
            boolean encontrado = pdao.validarId(id);
            
            if(encontrado){    
                Persona persona = pdao.buscarPersonaPorId(id);
                txtNombre.setText(persona.getNombres());
                txtApellidos.setText(persona.getApellido());
                txtEdad.setText(persona.getEdad() + "");
                txtTelefono.setText(persona.getTelefono());
                JOptionPane.showMessageDialog(null, "Busqueda exitosa");
            }else{
                JOptionPane.showMessageDialog(null, "El ID: " + id + " no existe");
                limpiarCampos();
            }
        }
    }//GEN-LAST:event_btnBuscarIdActionPerformed

    private void btnBuscarNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombresActionPerformed
        if(txtNombre.getText().equals("")){
            JOptionPane.showMessageDialog(null, "El campo de nombre esta vacio");
            mostrarTabla("");
        }else{
            mostrarTabla(txtNombre.getText());
        }
    }//GEN-LAST:event_btnBuscarNombresActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        FrmLogin frmLogin = new FrmLogin();
        frmLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    

    private void limpiarCampos() {
        txtId.setText(pdao.getIdIncremental());
        txtNombre.setText("");
        txtApellidos.setText("");
        txtEdad.setText("");
        txtTelefono.setText("");
        mostrarTabla("");
    }

    private void mostrarTabla(String nombres) {
        pdao.listarPersonas(tblPersonaDatos, nombres);
        tblPersonaDatos.repaint();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarId;
    private javax.swing.JButton btnBuscarNombres;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel paneFrmPersona;
    private javax.swing.JScrollPane scpPersonaDatos;
    private javax.swing.JTable tblPersonaDatos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
