/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.unadm.mexican.food.restaurant.views;

import java.util.logging.Level;
import java.util.logging.Logger;
import lombok.Getter;
import lombok.Setter;
import mx.com.unadm.mexican.food.restaurant.controllers.EmpleadoController;
import mx.com.unadm.mexican.food.restaurant.exceptions.NonexistentEntityException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Clase que define la interfaz grafica para los empleados 
 * @author Josue Palemon Perez
 * @version 1.0
 */
@Component
@Getter
@Setter
public class FrmEmpleado extends javax.swing.JFrame {

    @Autowired
    private EmpleadoController controller;
    
    
    /**
     * Creates new form FrmEmpleado
     */
    public FrmEmpleado() { }
    
    public void showComponents() {
        initComponents();
        this.setTitle("Formulario Empleados");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        mostrarTabla("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEmpleado = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblRfc = new javax.swing.JLabel();
        lblCurp = new javax.swing.JLabel();
        lblApellidoPaterno = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblApellidoMaterno = new javax.swing.JLabel();
        lblCorreoElectronico = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblSalario = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtRfc = new javax.swing.JTextField();
        txtCurp = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtCorreoElectronico = new javax.swing.JTextField();
        txtSalario = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        scpTblEmpleado = new javax.swing.JScrollPane();
        tblEmpleadoData = new javax.swing.JTable();
        btnBuscarNombre = new javax.swing.JButton();
        btnBuscarNumero = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        pnlEmpleado.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitulo.setText("Formulario Empleado");
        pnlEmpleado.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 17, -1, -1));

        lblNumero.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblNumero.setText("Numero:");
        pnlEmpleado.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, -1, -1));

        lblRfc.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblRfc.setText("RFC:");
        pnlEmpleado.add(lblRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 197, -1, -1));

        lblCurp.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCurp.setText("CURP:");
        pnlEmpleado.add(lblCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 146, -1, -1));

        lblApellidoPaterno.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblApellidoPaterno.setText("A. Paterno:");
        pnlEmpleado.add(lblApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 243, -1, -1));

        lblNombre.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblNombre.setText("Nombre:");
        pnlEmpleado.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 100, -1, -1));

        lblApellidoMaterno.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblApellidoMaterno.setText("A. Materno:");
        pnlEmpleado.add(lblApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 286, -1, -1));

        lblCorreoElectronico.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCorreoElectronico.setText("C. Electronico:");
        pnlEmpleado.add(lblCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 335, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTelefono.setText("Telefono:");
        pnlEmpleado.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 381, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblDireccion.setText("Salario:");
        pnlEmpleado.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 470, -1, -1));

        lblSalario.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblSalario.setText("Direccion:");
        pnlEmpleado.add(lblSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 427, -1, -1));

        txtNumero.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlEmpleado.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 57, 111, -1));

        txtTelefono.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlEmpleado.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 378, 195, -1));

        txtRfc.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlEmpleado.add(txtRfc, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 194, 239, -1));

        txtCurp.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlEmpleado.add(txtCurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 143, 239, -1));

        txtNombre.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlEmpleado.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 97, 111, -1));

        txtApellidoMaterno.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlEmpleado.add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 286, 189, -1));

        txtCorreoElectronico.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlEmpleado.add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 332, 162, -1));

        txtSalario.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlEmpleado.add(txtSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 464, 218, -1));

        txtDireccion.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlEmpleado.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 424, 200, -1));

        txtApellidoPaterno.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlEmpleado.add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 240, 188, -1));

        btnGuardar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlEmpleado.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        btnModificar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        pnlEmpleado.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlEmpleado.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, -1, -1));

        tblEmpleadoData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblEmpleadoData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadoDataMouseClicked(evt);
            }
        });
        scpTblEmpleado.setViewportView(tblEmpleadoData);

        pnlEmpleado.add(scpTblEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 69, 560, 340));

        btnBuscarNombre.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBuscarNombre.setText("Buscar");
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });
        pnlEmpleado.add(btnBuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 97, -1, -1));

        btnBuscarNumero.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBuscarNumero.setText("Buscar");
        btnBuscarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNumeroActionPerformed(evt);
            }
        });
        pnlEmpleado.add(btnBuscarNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 57, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        pnlEmpleado.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, -1, -1));

        getContentPane().add(pnlEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            controller.guardarEmpleado(evt);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            controller.modificarEmpleado(evt);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(FrmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        controller.eliminarEmpleado(evt);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void tblEmpleadoDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadoDataMouseClicked
        controller.selectedRowEmpleadoTabla(evt);
    }//GEN-LAST:event_tblEmpleadoDataMouseClicked

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        controller.buscarEmpleadoPorNombre();
    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNumeroActionPerformed
        controller.buscarEmpleadoPorNumero();
    }//GEN-LAST:event_btnBuscarNumeroActionPerformed

    
    public void mostrarTabla(String nombre) {
        controller.listarEmpleadosTabla(tblEmpleadoData, nombre);
        tblEmpleadoData.repaint();
    }
    
    
    public void limpiarCampos() {
        txtNumero.setText("");
        txtRfc.setText("");
        txtCurp.setText("");
        txtNombre.setText("");
        txtApellidoPaterno.setText("");
        txtApellidoMaterno.setText("");
        txtCorreoElectronico.setText("");
        txtTelefono.setText("");
        txtDireccion.setText("");
        txtSalario.setText("");
        mostrarTabla("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnBuscarNumero;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel lblApellidoMaterno;
    private javax.swing.JLabel lblApellidoPaterno;
    private javax.swing.JLabel lblCorreoElectronico;
    private javax.swing.JLabel lblCurp;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblRfc;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlEmpleado;
    private javax.swing.JScrollPane scpTblEmpleado;
    private javax.swing.JTable tblEmpleadoData;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JTextField txtCurp;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRfc;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
