/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.unadm.mexican.food.restaurant.views;

import java.util.logging.Level;
import java.util.logging.Logger;
import lombok.Getter;
import lombok.Setter;
import mx.com.unadm.mexican.food.restaurant.controllers.NominaController;
import mx.com.unadm.mexican.food.restaurant.exceptions.NonexistentEntityException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Define la interfaz grafica para las nominas 
 * @author Josue Palemon Perez
 * @version 1.0
 */
@Component
@Getter
@Setter
public class FrmNomina extends javax.swing.JFrame {

    
    @Autowired
    private NominaController controller;
    
    /**
     * Creates new form FrmNomina
     */
    public FrmNomina() { }
    
    public void showComponents() {
//        limpiarCampos();
        initComponents();
        this.setTitle("Formulario Nominas");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        mostrarTabla("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNomina = new javax.swing.JPanel();
        lblNumero = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblRazonSocial = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JTextField();
        lblDomicilio = new javax.swing.JLabel();
        txtDomicilio = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblPeriodoInicio = new javax.swing.JLabel();
        txtPeriodoInicio = new javax.swing.JTextField();
        txtPeriodoFin = new javax.swing.JTextField();
        lblPeriodoFin = new javax.swing.JLabel();
        scpTblNomina = new javax.swing.JScrollPane();
        tblNominaData = new javax.swing.JTable();
        btnBuscarRazonSocial = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblDias = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBuscarNumero = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNomina.setForeground(new java.awt.Color(255, 255, 255));
        pnlNomina.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNumero.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblNumero.setText("Numero:");
        pnlNomina.add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitulo.setText("Formulario Nomina");
        pnlNomina.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        txtNumero.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlNomina.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 180, -1));

        lblRazonSocial.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblRazonSocial.setText("R. Social:");
        pnlNomina.add(lblRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtRazonSocial.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlNomina.add(txtRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 180, -1));

        lblDomicilio.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblDomicilio.setText("Domicilio:");
        pnlNomina.add(lblDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtDomicilio.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlNomina.add(txtDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 278, -1));

        lblFecha.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblFecha.setText("Fecha:");
        pnlNomina.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtFecha.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlNomina.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 311, -1));

        lblPeriodoInicio.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblPeriodoInicio.setText("Periodo Inicio:");
        pnlNomina.add(lblPeriodoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 245, -1, -1));

        txtPeriodoInicio.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlNomina.add(txtPeriodoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 242, 238, -1));

        txtPeriodoFin.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlNomina.add(txtPeriodoFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 276, 238, -1));

        lblPeriodoFin.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblPeriodoFin.setText("Periodo Fin:");
        pnlNomina.add(lblPeriodoFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 279, -1, -1));

        tblNominaData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblNominaData.setSize(new java.awt.Dimension(150, 80));
        tblNominaData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNominaDataMouseClicked(evt);
            }
        });
        scpTblNomina.setViewportView(tblNominaData);

        pnlNomina.add(scpTblNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 54, 505, 250));

        btnBuscarRazonSocial.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        btnBuscarRazonSocial.setText("Buscar");
        btnBuscarRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRazonSocialActionPerformed(evt);
            }
        });
        pnlNomina.add(btnBuscarRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        btnModificar.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        pnlNomina.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, -1, -1));

        btnEliminar.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlNomina.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        lblDias.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblDias.setText("Dias:");
        pnlNomina.add(lblDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        txtDias.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlNomina.add(txtDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 310, -1));

        btnGuardar.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlNomina.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        btnBuscarNumero.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        btnBuscarNumero.setText("Buscar");
        btnBuscarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNumeroActionPerformed(evt);
            }
        });
        pnlNomina.add(btnBuscarNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        btnLimpiar.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        pnlNomina.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        getContentPane().add(pnlNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRazonSocialActionPerformed
        controller.buscarNominaPorRazonSocial();
    }//GEN-LAST:event_btnBuscarRazonSocialActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            controller.modificarNomina(evt);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(FrmNomina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        controller.eliminarNomina(evt);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            controller.guardarNomina(evt);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(FrmNomina.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNumeroActionPerformed
        controller.buscarNominaPorNumero();
    }//GEN-LAST:event_btnBuscarNumeroActionPerformed

    private void tblNominaDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNominaDataMouseClicked
        controller.selectedRowNominaTabla(evt);
    }//GEN-LAST:event_tblNominaDataMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

     public void mostrarTabla(String numero) {
        controller.listarNominasTabla(tblNominaData, numero);
        tblNominaData.repaint();
    }
    
    
    public void limpiarCampos() {
        txtNumero.setText("");
        txtRazonSocial.setText("");
        
        txtDomicilio.setText("");
        txtFecha.setText("");
        txtPeriodoInicio.setText("");
        txtPeriodoFin.setText("");
        txtDias.setText("");
        mostrarTabla("");
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarNumero;
    private javax.swing.JButton btnBuscarRazonSocial;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPeriodoFin;
    private javax.swing.JLabel lblPeriodoInicio;
    private javax.swing.JLabel lblRazonSocial;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlNomina;
    private javax.swing.JScrollPane scpTblNomina;
    private javax.swing.JTable tblNominaData;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtDomicilio;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPeriodoFin;
    private javax.swing.JTextField txtPeriodoInicio;
    private javax.swing.JTextField txtRazonSocial;
    // End of variables declaration//GEN-END:variables
}
