/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.unadm.mexican.food.restaurant.views;

import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import lombok.Getter;
import lombok.Setter;
import mx.com.unadm.mexican.food.restaurant.controllers.ReporteController;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Clase que genera la vista para la pantalla principal de la aplicacion
 *
 * @author Josue Palemon Perez
 * @version 1.0
 */
@Component
@Getter
@Setter
public class FrmPrincipal extends javax.swing.JFrame {

    @Autowired
    private FrmRestaurante restauranteView;
    @Autowired
    private FrmEmpleado empleadoView;
    @Autowired
    private FrmNomina nominaView;
    @Autowired 
    private FrmProducto productoView;
    @Autowired
    private ReporteController reporteController;
    

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
    }

    public void showComponents() {
        initComponents();
        loadLogo();
        this.setTitle("Aplicacion Restaurante Mexicano");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        nmbPrincipal = new javax.swing.JMenuBar();
        mnuRestaurantes = new javax.swing.JMenu();
        mniFrmRestaurantes = new javax.swing.JMenuItem();
        mnuEmpleados = new javax.swing.JMenu();
        mniFrmEmpleados = new javax.swing.JMenuItem();
        mnuProductos = new javax.swing.JMenu();
        mniFrmProductos = new javax.swing.JMenuItem();
        mnuNomina = new javax.swing.JMenu();
        mniFrmNomina = new javax.swing.JMenuItem();
        mnuReportes = new javax.swing.JMenu();
        mniReportesRestaurantes = new javax.swing.JMenuItem();
        mniReportesEmpleados = new javax.swing.JMenuItem();
        mniReportesProductos = new javax.swing.JMenuItem();
        mniReportesNomina = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPrincipal.setBackground(new java.awt.Color(162, 162, 162));
        pnlPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlPrincipal.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 430, 230));

        getContentPane().add(pnlPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 330));

        mnuRestaurantes.setText("Restaurantes");

        mniFrmRestaurantes.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        mniFrmRestaurantes.setText("Formulario Restaurantes");
        mniFrmRestaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFrmRestaurantesActionPerformed(evt);
            }
        });
        mnuRestaurantes.add(mniFrmRestaurantes);

        nmbPrincipal.add(mnuRestaurantes);

        mnuEmpleados.setText("Empleados");

        mniFrmEmpleados.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        mniFrmEmpleados.setText("Formulario Empleados");
        mniFrmEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFrmEmpleadosActionPerformed(evt);
            }
        });
        mnuEmpleados.add(mniFrmEmpleados);

        nmbPrincipal.add(mnuEmpleados);

        mnuProductos.setText("Productos");

        mniFrmProductos.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        mniFrmProductos.setText("Formulario Productos");
        mniFrmProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFrmProductosActionPerformed(evt);
            }
        });
        mnuProductos.add(mniFrmProductos);

        nmbPrincipal.add(mnuProductos);

        mnuNomina.setText("Nomina");

        mniFrmNomina.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        mniFrmNomina.setText("Formulario Nomina");
        mniFrmNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniFrmNominaActionPerformed(evt);
            }
        });
        mnuNomina.add(mniFrmNomina);

        nmbPrincipal.add(mnuNomina);

        mnuReportes.setText("Reportes");

        mniReportesRestaurantes.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        mniReportesRestaurantes.setText("Reportes Restaurantes");
        mniReportesRestaurantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReportesRestaurantesActionPerformed(evt);
            }
        });
        mnuReportes.add(mniReportesRestaurantes);

        mniReportesEmpleados.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        mniReportesEmpleados.setText("Reportes Empleados");
        mniReportesEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReportesEmpleadosActionPerformed(evt);
            }
        });
        mnuReportes.add(mniReportesEmpleados);

        mniReportesProductos.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        mniReportesProductos.setText("Reportes Productos");
        mniReportesProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReportesProductosActionPerformed(evt);
            }
        });
        mnuReportes.add(mniReportesProductos);

        mniReportesNomina.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        mniReportesNomina.setText("Reportes Nomina ");
        mniReportesNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniReportesNominaActionPerformed(evt);
            }
        });
        mnuReportes.add(mniReportesNomina);

        nmbPrincipal.add(mnuReportes);

        setJMenuBar(nmbPrincipal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniFrmRestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFrmRestaurantesActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            restauranteView.setVisible(true);
            restauranteView.showComponents();
            }
        });
    }//GEN-LAST:event_mniFrmRestaurantesActionPerformed

    private void mniFrmEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFrmEmpleadosActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
            empleadoView.setVisible(true);
            empleadoView.showComponents();
            }
        });
    }//GEN-LAST:event_mniFrmEmpleadosActionPerformed

    private void mniFrmProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFrmProductosActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            productoView.setVisible(true);
            productoView.showComponents();
        });
    }//GEN-LAST:event_mniFrmProductosActionPerformed

    private void mniFrmNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniFrmNominaActionPerformed
        java.awt.EventQueue.invokeLater(() -> {
            nominaView.setVisible(true);
            nominaView.showComponents();
        });
    }//GEN-LAST:event_mniFrmNominaActionPerformed

    private void mniReportesEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReportesEmpleadosActionPerformed
        reporteController.generarReporteEmpleado();
    }//GEN-LAST:event_mniReportesEmpleadosActionPerformed

    private void mniReportesProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReportesProductosActionPerformed
        reporteController.generarReporteProducto();
    }//GEN-LAST:event_mniReportesProductosActionPerformed

    private void mniReportesNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReportesNominaActionPerformed
        reporteController.generarReporteNomina();
    }//GEN-LAST:event_mniReportesNominaActionPerformed

    private void mniReportesRestaurantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniReportesRestaurantesActionPerformed
        reporteController.generarReporteRestaurante();
    }//GEN-LAST:event_mniReportesRestaurantesActionPerformed

    private void loadLogo() {
        try {
            File cwd = new File("src/main/resources/images/mexican-restaurant-logo.png");
            BufferedImage wPic = ImageIO.read(cwd);
            lblLogo.setIcon(new ImageIcon(wPic));
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "No se cargo la imagen de logo de la aplicacion");
            Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private javax.swing.JMenuItem mniFrmEmpleados;
    private javax.swing.JMenuItem mniFrmNomina;
    private javax.swing.JMenuItem mniFrmProductos;
    private javax.swing.JMenuItem mniFrmRestaurantes;
    private javax.swing.JMenuItem mniReportesEmpleados;
    private javax.swing.JMenuItem mniReportesNomina;
    private javax.swing.JMenuItem mniReportesProductos;
    private javax.swing.JMenuItem mniReportesRestaurantes;
    private javax.swing.JMenu mnuEmpleados;
    private javax.swing.JMenu mnuNomina;
    private javax.swing.JMenu mnuProductos;
    private javax.swing.JMenu mnuReportes;
    private javax.swing.JMenu mnuRestaurantes;
    private javax.swing.JMenuBar nmbPrincipal;
    private javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
