/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.com.unadm.mexican.food.restaurant.views;

import java.util.logging.Level;
import java.util.logging.Logger;
import lombok.Getter;
import lombok.Setter;
import mx.com.unadm.mexican.food.restaurant.controllers.ProductoController;
import mx.com.unadm.mexican.food.restaurant.exceptions.NonexistentEntityException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Clase que define la  interfaz grafica para los productos
 * @author Josue Palemon Perez
 * @version 1.0
 */
@Component
@Getter
@Setter
public class FrmProducto extends javax.swing.JFrame {

    
    @Autowired
    private ProductoController controller;
    
    /**
     * Creates new form FrmProductos
     */
    public FrmProducto() {
    }
    
    public void showComponents() {
//        limpiarCampos();
        initComponents();
        this.setTitle("Formulario Productos");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        mostrarTabla("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlProductos = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBuscarNombre = new javax.swing.JButton();
        scpTblProducto = new javax.swing.JScrollPane();
        tblProductoData = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();
        btnBuscarCodigo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitulo.setText("Formulario Producto");
        pnlProductos.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, -1, -1));

        lblCodigo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCodigo.setText("Codigo:");
        pnlProductos.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 45, -1, -1));

        lblPrecio.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblPrecio.setText("Precio:");
        pnlProductos.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        lblDescripcion.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblDescripcion.setText("Descripcion:");
        pnlProductos.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        lblNombre.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblNombre.setText("Nombre:");
        pnlProductos.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, -1, -1));

        lblCantidad.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblCantidad.setText("Cantidad:");
        pnlProductos.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlProductos.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 100, -1));

        txtNombre.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlProductos.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 100, -1));

        txtDescripcion.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlProductos.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, -1));

        txtCantidad.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlProductos.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 180, -1));

        txtPrecio.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        pnlProductos.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 210, -1));

        btnEliminar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlProductos.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        btnModificar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        pnlProductos.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        btnBuscarNombre.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBuscarNombre.setText("Buscar");
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });
        pnlProductos.add(btnBuscarNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        tblProductoData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblProductoData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductoDataMouseClicked(evt);
            }
        });
        scpTblProducto.setViewportView(tblProductoData);

        pnlProductos.add(scpTblProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 400, 229));

        btnGuardar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        pnlProductos.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        btnBuscarCodigo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnBuscarCodigo.setText("Buscar");
        btnBuscarCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCodigoActionPerformed(evt);
            }
        });
        pnlProductos.add(btnBuscarCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        btnLimpiar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        pnlProductos.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, -1, -1));

        getContentPane().add(pnlProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        try {
            controller.modificarProducto(evt);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(FrmProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        controller.eliminarProducto(evt);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            controller.guardarProducto(evt);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(FrmProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCodigoActionPerformed
        controller.buscarProductoPorCodigo();
    }//GEN-LAST:event_btnBuscarCodigoActionPerformed

    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        controller.buscarProductoPorNombre();
    }//GEN-LAST:event_btnBuscarNombreActionPerformed

    private void tblProductoDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductoDataMouseClicked
        controller.selectedRowProductoTabla(evt);
    }//GEN-LAST:event_tblProductoDataMouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    
        
    public void mostrarTabla(String nombre) {
        controller.listarProductosTabla(tblProductoData, nombre);
        tblProductoData.repaint();
    }
    
    
    public void limpiarCampos() {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
        mostrarTabla("");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCodigo;
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlProductos;
    private javax.swing.JScrollPane scpTblProducto;
    private javax.swing.JTable tblProductoData;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
