/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

/**
 *
 * @author macos
 */
public class FrmInventarioBajas extends javax.swing.JFrame {

    /**
     * Creates new form FrmInventario
     */
    public FrmInventarioBajas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInvetariosBajas = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblArticulo = new javax.swing.JLabel();
        txtArticulo = new javax.swing.JTextField();
        lblTituloBajas = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlInvetariosBajas.setBackground(new java.awt.Color(255, 255, 255));
        pnlInvetariosBajas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigo.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigo.setText("Código:");
        pnlInvetariosBajas.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 34, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        pnlInvetariosBajas.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 30, 227, -1));

        lblArticulo.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblArticulo.setForeground(new java.awt.Color(0, 0, 0));
        lblArticulo.setText("Artículo:");
        pnlInvetariosBajas.add(lblArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 86, -1, -1));

        txtArticulo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        pnlInvetariosBajas.add(txtArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 82, 227, -1));

        lblTituloBajas.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTituloBajas.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloBajas.setText("Bajas");
        pnlInvetariosBajas.add(lblTituloBajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, 24));

        btnEliminar.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        pnlInvetariosBajas.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 143, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        pnlInvetariosBajas.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 143, -1, -1));

        getContentPane().add(pnlInvetariosBajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInventarioBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInventarioBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInventarioBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInventarioBajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInventarioBajas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel lblArticulo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblTituloBajas;
    private javax.swing.JPanel pnlInvetariosBajas;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
