/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

/**
 *
 * @author macos
 */
public class FrmInventarioAltas extends javax.swing.JFrame {

    /**
     * Creates new form FrmInventario
     */
    public FrmInventarioAltas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInventarioAltas = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblArticulo = new javax.swing.JLabel();
        txtArticulo = new javax.swing.JTextField();
        lblSucursal = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblExistencia = new javax.swing.JLabel();
        txtExistencia = new javax.swing.JTextField();
        txtSucursal = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        lblTituloInventarioAltas = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlInventarioAltas.setBackground(new java.awt.Color(255, 255, 255));
        pnlInventarioAltas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigo.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblCodigo.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigo.setText("Código:");
        pnlInventarioAltas.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 34, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));
        pnlInventarioAltas.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 30, 227, -1));

        lblArticulo.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblArticulo.setForeground(new java.awt.Color(0, 0, 0));
        lblArticulo.setText("Artículo:");
        pnlInventarioAltas.add(lblArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 86, -1, -1));

        txtArticulo.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtArticulo.setForeground(new java.awt.Color(0, 0, 0));
        pnlInventarioAltas.add(txtArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 227, -1));

        lblSucursal.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblSucursal.setForeground(new java.awt.Color(0, 0, 0));
        lblSucursal.setText("Sucursal:");
        pnlInventarioAltas.add(lblSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 142, -1, -1));

        lblMarca.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(0, 0, 0));
        lblMarca.setText("Marca:");
        pnlInventarioAltas.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 251, -1, -1));

        lblExistencia.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblExistencia.setForeground(new java.awt.Color(0, 0, 0));
        lblExistencia.setText("Existencia:");
        pnlInventarioAltas.add(lblExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 203, -1, -1));

        txtExistencia.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtExistencia.setForeground(new java.awt.Color(0, 0, 0));
        pnlInventarioAltas.add(txtExistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 199, 227, -1));

        txtSucursal.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtSucursal.setForeground(new java.awt.Color(0, 0, 0));
        txtSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSucursalActionPerformed(evt);
            }
        });
        pnlInventarioAltas.add(txtSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 138, 227, -1));

        txtMarca.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        txtMarca.setForeground(new java.awt.Color(0, 0, 0));
        pnlInventarioAltas.add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 247, 227, -1));

        lblTituloInventarioAltas.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTituloInventarioAltas.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloInventarioAltas.setText("Altas");
        pnlInventarioAltas.add(lblTituloInventarioAltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 0, -1, 24));

        btnAgregar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("Agregar");
        pnlInventarioAltas.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 307, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlInventarioAltas.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 307, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInventarioAltas, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlInventarioAltas, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSucursalActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInventarioAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInventarioAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInventarioAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInventarioAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInventarioAltas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblArticulo;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblExistencia;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblSucursal;
    private javax.swing.JLabel lblTituloInventarioAltas;
    private javax.swing.JPanel pnlInventarioAltas;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtExistencia;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtSucursal;
    // End of variables declaration//GEN-END:variables
}
