/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

/**
 *
 * @author macos
 */
public class FrmPersonalAltas extends javax.swing.JFrame {

    /**
     * Creates new form FrmInventario
     */
    public FrmPersonalAltas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPersonalAltas = new javax.swing.JPanel();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApellidos = new javax.swing.JLabel();
        lblPuesto = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtPuesto = new javax.swing.JTextField();
        lblTituloAltas = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtArea = new javax.swing.JTextField();
        lblArea = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlPersonalAltas.setBackground(new java.awt.Color(255, 255, 255));
        pnlPersonalAltas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMatricula.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblMatricula.setForeground(new java.awt.Color(0, 0, 0));
        lblMatricula.setText("Matricula:");
        pnlPersonalAltas.add(lblMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        txtMatricula.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        pnlPersonalAltas.add(txtMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 227, -1));

        lblNombres.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblNombres.setForeground(new java.awt.Color(0, 0, 0));
        lblNombres.setText("Nombres:");
        pnlPersonalAltas.add(lblNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtNombres.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        pnlPersonalAltas.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 227, -1));

        lblApellidos.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblApellidos.setForeground(new java.awt.Color(0, 0, 0));
        lblApellidos.setText("Apellidos:");
        pnlPersonalAltas.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 142, -1, -1));

        lblPuesto.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblPuesto.setForeground(new java.awt.Color(0, 0, 0));
        lblPuesto.setText("Puesto:");
        pnlPersonalAltas.add(lblPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 235, -1, -1));

        lblEdad.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblEdad.setForeground(new java.awt.Color(0, 0, 0));
        lblEdad.setText("Edad:");
        pnlPersonalAltas.add(lblEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 190, -1, -1));

        txtEdad.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        pnlPersonalAltas.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 227, -1));

        txtApellidos.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });
        pnlPersonalAltas.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 227, -1));

        txtPuesto.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        pnlPersonalAltas.add(txtPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 230, -1));

        lblTituloAltas.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTituloAltas.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloAltas.setText("Altas");
        pnlPersonalAltas.add(lblTituloAltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, -1, 24));

        btnAgregar.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnAgregar.setText("Agregar");
        pnlPersonalAltas.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, -1, -1));

        btnCancelar.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlPersonalAltas.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        txtArea.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        pnlPersonalAltas.add(txtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 227, -1));

        lblArea.setFont(new java.awt.Font("Lucida Sans", 1, 18)); // NOI18N
        lblArea.setForeground(new java.awt.Color(0, 0, 0));
        lblArea.setText("Area:");
        pnlPersonalAltas.add(lblArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        getContentPane().add(pnlPersonalAltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPersonalAltas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPersonalAltas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblArea;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblPuesto;
    private javax.swing.JLabel lblTituloAltas;
    private javax.swing.JPanel pnlPersonalAltas;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtArea;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPuesto;
    // End of variables declaration//GEN-END:variables
}
